create or replace view public.view_league_scoring_settings as
select
  game_key,
  max(league_key) as league_key,
  max("2_pt") as "rush_2pt",
  max("2_pt") as "pass_2pt",
  max("2_pt") as "rec_2pt",
  -- max("3_and_outs") as "3_and_outs",
  -- max("40_yd_comp") as "40_yd_comp",
  -- max("40_yd_pass_td") as "40_yd_pass_td",
  -- max("40_yd_rec") as "40_yd_rec",
  -- max("40_yd_rec_td") as "40_yd_rec_td",
  -- max("40_yd_rush") as "40_yd_rush",
  -- max("40_yd_rush_td") as "40_yd_rush_td",
  -- max("4_dwn_stops") as "4_dwn_stops",
  max("blk_kick") as "blk_kick",
  -- max("comp") as "comp",
  -- max("def_yds_allow") as "def_yds_allow",
  -- max("fg_0_19") as "fg_0_19",
  -- max("fg_20_29") as "fg_20_29",
  -- max("fg_30_39") as "fg_30_39",
  -- max("fg_40_49") as "fg_40_49",
  -- max("fg_50_") as "fg_50_",
  -- max("fg_made") as "fg_made",
  max("fg_miss") as "fgmiss",
  max("fg_yds") as "fgm_yds",
  max("fgm_0_19") as "fgm_0_19",
  max("fgm_20_29") as "fgm_20_29",
  max("fgm_30_39") as "fgm_30_39",
  max("fgm_40_49") as "fgm_40_49",
  max("fgm_50_") as "fgm_50p",
  max("fum") as "fum",
  max("fum_force") as "ff",
  max("fum_force") as "def_st_ff",
  max("fum_force") as "st_ff",
  max("fum_lost") as "fum_lost",
  max("fum_rec") as "st_fum_rec",
  max("fum_rec") as "def_st_fum_rec",
  max("fum_rec") as "fum_rec",
  max("fum_ret_td") as "fum_rec_td",
  -- max("gp") as "gp",
  -- max("inc") as "inc",
  max("int") as "pass_int",
  max("int") as "int",
  -- max("pass_1st_downs") as "pass_1st_downs",
  -- max("pass_att") as "pass_att",
  -- max("pass_def") as "pass_def",
  max("pass_td") as "pass_td",
  max("pass_yds") as "pass_yd",
  max("pat_made") as "xpm",
  max("pat_miss") as "xpmiss",
  -- max("pick_six") as "pick_six",
  -- max("pts_allow") as "pts_allow",
  max("pts_allow_0") as "pts_allow_0",
  max("pts_allow_14_20") as "pts_allow_14_20",
  max("pts_allow_1_6") as "pts_allow_1_6",
  max("pts_allow_21_27") as "pts_allow_21_27",
  max("pts_allow_28_34") as "pts_allow_28_34",
  max("pts_allow_35_") as "pts_allow_35p",
  max("pts_allow_7_13") as "pts_allow_7_13",
  max("rec") as "rec",
  -- max("rec_1st_downs") as "rec_1st_downs",
  max("rec_td") as "rec_td",
  max("rec_yds") as "rec_yd",
  -- max("ret_td") as "st_td",
  -- max("ret_yds") as "ret_yds",
  -- max("rush_1st_downs") as "rush_1st_downs",
  -- max("rush_att") as "rush_att",
  max("rush_td") as "rush_td",
  max("rush_yds") as "rush_yd",
  max("sack") as "sack",
  max("safe") as "safe",
  -- max("tack_ast") as "tack_ast",
  -- max("tack_solo") as "tack_solo",
  -- max("targets") as "targets",
  -- max("td") as "td",
  max("td") as "def_st_td",
  max("td") as "def_td"
  -- ,max("tfl") as "tfl",
  -- max("to_ret_yds") as "to_ret_yds",
  -- max("xpr") as "xpr",
  -- max("yds_allow_0_99") as "yds_allow_0_99",
  -- max("yds_allow_100_199") as "yds_allow_100_199",
  -- max("yds_allow_200_299") as "yds_allow_200_299",
  -- max("yds_allow_300_399") as "yds_allow_300_399",
  -- max("yds_allow_400_499") as "yds_allow_400_499",
  -- max("yds_allow_500_") as "yds_allow_500_",
  -- max("yds_allow_neg") as "yds_allow_neg"
from crosstab(
  'select game_key, league_key, display_name, stat_modifier from public.view_league_scoring_settings_unpivoted order by 3',
  'select distinct display_name from public.view_league_scoring_settings_unpivoted'
) as ct(
  game_key text,
  league_key text,
  "2_pt" decimal(4, 2),
  "3_and_outs" decimal(4, 2),
  "40_yd_comp" decimal(4, 2),
  "40_yd_pass_td" decimal(4, 2),
  "40_yd_rec" decimal(4, 2),
  "40_yd_rec_td" decimal(4, 2),
  "40_yd_rush" decimal(4, 2),
  "40_yd_rush_td" decimal(4, 2),
  "4_dwn_stops" decimal(4, 2),
  "blk_kick" decimal(4, 2),
  "comp" decimal(4, 2),
  "def_yds_allow" decimal(4, 2),
  "fg_0_19" decimal(4, 2),
  "fg_20_29" decimal(4, 2),
  "fg_30_39" decimal(4, 2),
  "fg_40_49" decimal(4, 2),
  "fg_50_" decimal(4, 2),
  "fg_made" decimal(4, 2),
  "fg_miss" decimal(4, 2),
  "fg_yds" decimal(4, 2),
  "fgm_0_19" decimal(4, 2),
  "fgm_20_29" decimal(4, 2),
  "fgm_30_39" decimal(4, 2),
  "fgm_40_49" decimal(4, 2),
  "fgm_50_" decimal(4, 2),
  "fum" decimal(4, 2),
  "fum_force" decimal(4, 2),
  "fum_lost" decimal(4, 2),
  "fum_rec" decimal(4, 2),
  "fum_ret_td" decimal(4, 2),
  "gp" decimal(4, 2),
  "inc" decimal(4, 2),
  "int" decimal(4, 2),
  "pass_1st_downs" decimal(4, 2),
  "pass_att" decimal(4, 2),
  "pass_def" decimal(4, 2),
  "pass_td" decimal(4, 2),
  "pass_yds" decimal(4, 2),
  "pat_made" decimal(4, 2),
  "pat_miss" decimal(4, 2),
  "pick_six" decimal(4, 2),
  "pts_allow" decimal(4, 2),
  "pts_allow_0" decimal(4, 2),
  "pts_allow_14_20" decimal(4, 2),
  "pts_allow_1_6" decimal(4, 2),
  "pts_allow_21_27" decimal(4, 2),
  "pts_allow_28_34" decimal(4, 2),
  "pts_allow_35_" decimal(4, 2),
  "pts_allow_7_13" decimal(4, 2),
  "rec" decimal(4, 2),
  "rec_1st_downs" decimal(4, 2),
  "rec_td" decimal(4, 2),
  "rec_yds" decimal(4, 2),
  "ret_td" decimal(4, 2),
  "ret_yds" decimal(4, 2),
  "rush_1st_downs" decimal(4, 2),
  "rush_att" decimal(4, 2),
  "rush_td" decimal(4, 2),
  "rush_yds" decimal(4, 2),
  "sack" decimal(4, 2),
  "safe" decimal(4, 2),
  "tack_ast" decimal(4, 2),
  "tack_solo" decimal(4, 2),
  "targets" decimal(4, 2),
  "td" decimal(4, 2),
  "tfl" decimal(4, 2),
  "to_ret_yds" decimal(4, 2),
  "xpr" decimal(4, 2),
  "yds_allow_0_99" decimal(4, 2),
  "yds_allow_100_199" decimal(4, 2),
  "yds_allow_200_299" decimal(4, 2),
  "yds_allow_300_399" decimal(4, 2),
  "yds_allow_400_499" decimal(4, 2),
  "yds_allow_500_" decimal(4, 2),
  "yds_allow_neg" decimal(4, 2)
)
group by game_key;
