create or replace view public.view_league as
select
  league.league_key as league_id,
  league.num_teams as total_rosters,
  league.league_key || '.draft' as draft_id,
  league.name,
  null::text as company_id,
  league.season,
  'regular' as season_type,
  league.game_code as sport,
  0 as shard,
  league.logo_url as avatar,
  null::varchar as last_message_id,
  null::varchar as last_read_id,
  null::varchar as last_pinned_message_id,
  null::int as last_message_time,
  null::varchar as last_message_text_map,
  null::varchar as last_message_attachment,
  null::boolean as last_author_is_bot,
  null::varchar as last_author_id,
  null::varchar as last_author_display_name,
  null::varchar as last_author_avatar,
  league.renew as previous_league_id,
  case when league.is_finished::int = 1 then 'complete' else 'in_season' end as status,
  case
    when league.season::int >= 2023 then array['QB', 'RB', 'RB', 'WR', 'WR', 'TE', 'FLEX', 'FLEX', 'DEF', 'BN', 'BN', 'BN', 'BN', 'BN', 'BN', 'IR']
    when league.season::int = 2020 then array['QB', 'RB', 'RB', 'WR', 'WR', 'TE', 'FLEX', 'K', 'DEF', 'BN', 'BN', 'BN', 'BN', 'BN', 'BN', 'IR', 'IR']
    else array['QB', 'RB', 'RB', 'WR', 'WR', 'TE', 'FLEX', 'K', 'DEF', 'BN', 'BN', 'BN', 'BN', 'BN', 'BN', 'IR']
    end as roster_positions,
  null::int as group_id,
  league.league_key || '.winners_bracket' as bracket_id,
  league.league_key || '.losers_bracket' as loser_bracket_id,
  jsonb_build_object(
    'rush_2pt', league_score."rush_2pt",
    'pass_2pt', league_score."pass_2pt",
    'rec_2pt', league_score."rec_2pt",
    'blk_kick', league_score."blk_kick",
    'fgmiss', league_score."fgmiss",
    'fgm_yds', league_score."fgm_yds",
    'fgm_0_19', league_score."fgm_0_19",
    'fgm_20_29', league_score."fgm_20_29",
    'fgm_30_39', league_score."fgm_30_39",
    'fgm_40_49', league_score."fgm_40_49",
    'fgm_50p', league_score."fgm_50p",
    'fum', league_score."fum",
    'ff', league_score."ff",
    'def_st_ff', league_score."def_st_ff",
    'st_ff', league_score."st_ff",
    'fum_lost', league_score."fum_lost",
    'st_fum_rec', league_score."st_fum_rec",
    'def_st_fum_rec', league_score."def_st_fum_rec",
    'fum_rec', league_score."fum_rec",
    'fum_rec_td', league_score."fum_rec_td",
    'pass_int', league_score."pass_int",
    'int', league_score."int",
    'pass_td', league_score."pass_td",
    'pass_yd', league_score."pass_yd",
    'xpm', league_score."xpm",
    'xpmiss', league_score."xpmiss",
    'pts_allow_0', league_score."pts_allow_0",
    'pts_allow_1_6', league_score."pts_allow_1_6",
    'pts_allow_7_13', league_score."pts_allow_7_13",
    'pts_allow_14_20', league_score."pts_allow_14_20",
    'pts_allow_21_27', league_score."pts_allow_21_27",
    'pts_allow_28_34', league_score."pts_allow_28_34",
    'pts_allow_35p', league_score."pts_allow_35p",
    'rec', league_score."rec",
    'rec_td', league_score."rec_td",
    'rec_yd', league_score."rec_yd",
    'rush_td', league_score."rush_td",
    'rush_yd', league_score."rush_yd",
    'sack', league_score."sack",
    'safe', league_score."safe",
    'def_st_td', league_score."def_st_td",
    'def_td', league_score."def_td"
  ) as scoring_settings,
  jsonb_build_object(
    'daily_waivers_last_ran', league_sett.daily_waivers_last_ran,
    'reserve_allow_cov', league_sett.reserve_allow_cov,
    'reserve_slots', league_sett.reserve_slots,
    'leg', league_sett.leg,
    'offseason_adds', league_sett.offseason_adds,
    'bench_lock', league_sett.bench_lock,
    'trade_review_days', league_sett.trade_review_days,
    'league_average_match', league_sett.league_average_match,
    'waiver_type', league_sett.waiver_type,
    'max_keepers', league_sett.max_keepers,
    'type', league_sett.type,
    'pick_trading', league_sett.pick_trading,
    'daily_waivers', league_sett.daily_waivers,
    'taxi_years', league_sett.taxi_years,
    'trade_deadline', league_sett.trade_deadline,
    'reserve_allow_sus', league_sett.reserve_allow_sus,
    'reserve_allow_out', league_sett.reserve_allow_out,
    'playoff_round_type', league_sett.playoff_round_type,
    'waiver_day_of_week', league_sett.waiver_day_of_week,
    'taxi_allow_vets', league_sett.taxi_allow_vets,
    'reserve_allow_dnr', league_sett.reserve_allow_dnr,
    'commissioner_direct_invite', league_sett.commissioner_direct_invite,
    'reserve_allow_doubtful', league_sett.reserve_allow_doubtful,
    'waiver_clear_days', league_sett.waiver_clear_days,
    'playoff_week_start', league_sett.playoff_week_start,
    'daily_waivers_days', league_sett.daily_waivers_days,
    'last_scored_leg', league_sett.last_scored_leg,
    'taxi_slots', league_sett.taxi_slots,
    'playoff_type', league_sett.playoff_type,
    'daily_waivers_hour', league_sett.daily_waivers_hour,
    'num_teams', league_sett.num_teams,
    'playoff_teams', league_sett.playoff_teams,
    'playoff_seed_type', league_sett.playoff_seed_type,
    'start_week', league_sett.start_week,
    'reserve_allow_na', league_sett.reserve_allow_na,
    'draft_rounds', league_sett.draft_rounds,
    'taxi_deadline', league_sett.taxi_deadline,
    'waiver_bid_min', league_sett.waiver_bid_min,
    'capacity_override', league_sett.capacity_override,
    'disable_adds', league_sett.disable_adds,
    'waiver_budget', league_sett.waiver_budget,
    'last_report', league_sett.last_report,
    'league_id', league_sett.league_id
  ) as settings,
  jsonb_build_object(
    'keeper_deadline', 0
  ) as metadata
from yahoo_data.view_leagues league
left join public.view_league_scoring_settings league_score
  on league_score.league_key = league.league_key
left join  public.view_league_settings league_sett
  on league_sett.league_id = league.league_key;
