create or replace view public.view_player_data as
select distinct on (player_key)
  player_key as player_id,
  -- college varchar,
  -- weight varchar,
  -- practice_description varchar,
  -- espn_id bigint,
  editorial_team_full_name as team,
  -- sportradar_id varchar,
  full_name,
  -- injury_status varchar,
  -- injury_start_date varchar,
  primary_position as position,
  -- birth_state varchar,
  -- rotowire_id bigint,
  -- swish_id bigint,
  jsonb_build_object(
    'rookie_year', null
  ) as metadata,
  -- oddsjam_id varchar,
  uniform_number::int as number,
  injury_note as injury_notes,
  first_ascii_name as search_first_name,
  -- hashtag varchar,
  string_to_array(eligible_positions, ',') as fantasy_positions,
  last_name,
  -- injury_body_part varchar,
  -- birth_city varchar,
  -- practice_participation varchar,
  -- age int,
  -- birth_country varchar,
  -- stats_id bigint,
  -- gsis_id varchar,
  -- pandascore_id varchar,
  -- status varchar,
  last_ascii_name as search_last_name,
  -- high_school varchar,
  'nfl' as sport,
  -- rotoworld_id int,
  player_notes_last_timestamp::bigint as news_updated,
  -- birth_date varchar,
  first_name,
  true as active,
  -- fantasy_data_id int,
  -- depth_chart_order int,
  -- years_exp int,
  -- height varchar,
  -- search_full_name varchar,
  player_id::bigint as yahoo_id
  -- search_rank bigint,
  -- depth_chart_position varchar
from yahoo_data.player_pct_owned
order by player_key, inserted_timestamp desc;
